config:
  # Options: True, False
  pos:
    noun: True
    verb: True
    adv: True
    adj: True
  # Options: True, False
  embedding: False
  # Options: count, tfidf
  vectorizer: count

paths:
  input:
    database: data-input/database
  output:
    database: data-output/database
    model: data-output/model

datasets:
  disease:
    file: Symptom2Disease.csv
    text: text
    category: label