config:
  # Options: True, False
  pos:
    noun: True
    verb: True
    adv: True
    adj: True

paths:
  input:
    database: data-input/database
  output:
    database: data-output/database
    model: data-output/model

datasets:
